version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "8088:8088"
      - "9088:9088"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

  restaurant-service:
    build:
      context: .
      dockerfile: services/restaurant-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    ports:
      - "8083:8083"
      - "8084:8084"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
      - USER_SERVICE_GRPC_URL=user-service:9088
      - RESTAURANT_SERVICE_GRPC_URL=restaurant-service:9082
    depends_on:
      - mongodb
      - rabbitmq

  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile
    ports:
      - "8085:8085"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mongodb
      - rabbitmq

  delivery-service:
    build:
      context: .
      dockerfile: services/delivery-service/Dockerfile
    ports:
      - "8086:8086"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mongodb
      - rabbitmq

  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    ports:
      - "8087:8087"
    environment:
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - USER_SERVICE_URL=http://user-service:8088
      - RESTAURANT_SERVICE_URL=http://restaurant-service:8082
      - ORDER_SERVICE_URL=http://order-service:8083
    depends_on:
      - auth-service
      - user-service
      - restaurant-service
      - order-service

volumes:
  mongodb_data:
