version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

  restaurant-service:
    build:
      context: ./services/restaurant-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    ports:
      - "8083:8083"
      - "8084:8084"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mongodb
      - rabbitmq

  payment-service:
    build:
      context: ./services
      dockerfile: payment-service/Dockerfile
    ports:
      - "8085:8085"
    environment:
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq

  delivery-service:
    build:
      context: ./services
      dockerfile: delivery-service/Dockerfile
    ports:
      - "8086:8086"
    environment:
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq

  notification-service:
    build:
      context: ./services
      dockerfile: notification-service/Dockerfile
    ports:
      - "8087:8087"
    environment:
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - restaurant-service
      - order-service

volumes:
  mongodb_data:
