// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: restaurant.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemRequest) Reset() {
	*x = GetMenuItemRequest{}
	mi := &file_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemRequest) ProtoMessage() {}

func (x *GetMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *GetMenuItemRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *GetMenuItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetMenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemResponse) Reset() {
	*x = GetMenuItemResponse{}
	mi := &file_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemResponse) ProtoMessage() {}

func (x *GetMenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemResponse.ProtoReflect.Descriptor instead.
func (*GetMenuItemResponse) Descriptor() ([]byte, []int) {
	return file_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *GetMenuItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMenuItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMenuItemResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_restaurant_proto protoreflect.FileDescriptor

const file_restaurant_proto_rawDesc = "" +
	"\n" +
	"\x10restaurant.proto\x12\n" +
	"restaurant\"R\n" +
	"\x12GetMenuItemRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\"O\n" +
	"\x13GetMenuItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price2c\n" +
	"\x11RestaurantService\x12N\n" +
	"\vGetMenuItem\x12\x1e.restaurant.GetMenuItemRequest\x1a\x1f.restaurant.GetMenuItemResponseB5Z3github.com/food_delivery_microservices_system/protob\x06proto3"

var (
	file_restaurant_proto_rawDescOnce sync.Once
	file_restaurant_proto_rawDescData []byte
)

func file_restaurant_proto_rawDescGZIP() []byte {
	file_restaurant_proto_rawDescOnce.Do(func() {
		file_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurant_proto_rawDesc), len(file_restaurant_proto_rawDesc)))
	})
	return file_restaurant_proto_rawDescData
}

var file_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_restaurant_proto_goTypes = []any{
	(*GetMenuItemRequest)(nil),  // 0: restaurant.GetMenuItemRequest
	(*GetMenuItemResponse)(nil), // 1: restaurant.GetMenuItemResponse
}
var file_restaurant_proto_depIdxs = []int32{
	0, // 0: restaurant.RestaurantService.GetMenuItem:input_type -> restaurant.GetMenuItemRequest
	1, // 1: restaurant.RestaurantService.GetMenuItem:output_type -> restaurant.GetMenuItemResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_restaurant_proto_init() }
func file_restaurant_proto_init() {
	if File_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurant_proto_rawDesc), len(file_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurant_proto_goTypes,
		DependencyIndexes: file_restaurant_proto_depIdxs,
		MessageInfos:      file_restaurant_proto_msgTypes,
	}.Build()
	File_restaurant_proto = out.File
	file_restaurant_proto_goTypes = nil
	file_restaurant_proto_depIdxs = nil
}
